---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: windows-2012r2

suites:
  - name: package
    run_list: 
      - recipe[dotnetcore::default]
    attributes:
    excludes:
      - windows-2012r2
  - name: winpackage
    run_list:
      - recipe[dotnetcore::default]
    attributes:
    excludes:
      - ubuntu-14.04
